kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs-volume-claim
spec:
  volumeName: logs-persistent-volume
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi