apiVersion: v1
kind: ConfigMap
metadata:
  name: citizen-gatewayapi-settings-env-production
  namespace: citizen-budget
data: 
  ocelot.Production.json: |-
    {
      "ReRoutes": [
        {
          "DownstreamPathTemplate": "/api/citizen/createcitizen/",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "service-citizen.citizen-budget",
              "Port": 5201
            }
          ],
          "UpstreamPathTemplate": "/api/citizen/createcitizen/",
          "UpstreamHttpMethod": [ "Post", "OPTIONS" ]
        }
      ]
    }
  appsettings.Production.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "TRACE"
        }
      },
      "host": {
        "port": "80",
        "server": "localhost"
      },
      "sekretkey": {
        "key": "dsffffffffffsdfdsfnuewfu34ufu34f34fbyb4yfb4y3fb3b4ybf3ybyfb3yf"
      }
    }