apiVersion: v1
kind: ConfigMap
metadata:
  name: citizen-gatewayapi-settings-env-production
  namespace: citizen-budget
data: 
  ocelot.Production.json: |-
    {
      "ReRoutes": [
        {
          "DownstreamPathTemplate": "/api/citizen/createcitizen/",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "service-citizen.citizen-budget",
              "Port": 5201
            }
          ],
          "UpstreamPathTemplate": "/api/citizen/createcitizen/",
          "UpstreamHttpMethod": [ "Post", "OPTIONS" ]
        }
      ]
    }
