apiVersion: v1
kind: Service
metadata:
  name: gatewayapi
  labels:
    name: gatewayapi
    environment: production
spec:
  type: NodePort
  ports:
  - nodePort: 31201
    name: external
    port: 80
    protocol: TCP
    targetPort: 80
  - port: 5201
    name: internal
    targetPort: 80
    protocol: TCP
  selector:
    role: gatewayapi
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gatewayapi
spec:
  serviceName: "gatewayapi"
  replicas: 1
  template:
    metadata:
      labels:
        role: gatewayapi
    spec:
      containers:
        - name: citizenbudget-gatewayapi
          image: lukasztomalczyk/citizenbudget.gatewayapi:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          volumeMounts:
          - name: config
            mountPath: /app/ocelot.Production.json
            subPath: ocelot.Production.json
      volumes:
      - name: config
        configMap:
          name: citizen-gatewayapi-settings-env-production
