apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
spec:
  selector:
    matchLabels:
      app: seq
  replicas: 1
  template:
    metadata:
      labels:
        app: seq
    spec:
      dnsPolicy: Default
      terminationGracePeriodSeconds: 10
      containers:
        - name: seq
          image: datalust/seq:latest
          ports:
            - containerPort: 5341
              name: connect
            - containerPort: 80
              name: ui
          volumeMounts:
            - name: seq-storage
              mountPath: /data
          env:
            - name: ACCEPT_EULA
              value: "Y"
      volumes:
        - name: seq-storage
          persistentVolumeClaim:
            claimName: seq-local-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seq-persistent-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/seq
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - develop-server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seq-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
---