apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-services-deployment
spec:
  selector:
    matchLabels:
      app: citizen.services
  replicas: 1
  template:
    metadata:
      labels:
        app: citizen.services
    spec:
      dnsPolicy: Default
      containers:
      - name: citizen
        image: lukasztomalczyk/citizenbudget.services.citizen:1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: CONSUL_HOST
            value: "10.152.183.81"
          - name: CONSUL_PORT
            value: "8500"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: citizen-service-settings-env-production
  namespace: citizen-budget
data: 
  appsettings.Production.json: |-
    {
      "consul": {
        "host": "10.152.183.81",
        "address": "/api/citizen/",
        "name": "services-citizen",
        "port": "8500",
        "serviceport": "5201"
      }
    }
