apiVersion: v1
kind: Service
metadata:
  name: service-citizen
  labels:
    name: service-citizen
spec:
  ports:
  - port: 5201
    targetPort: 5201
  #clusterIP: None
  selector:
    role: services.citizen
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: service-citizen
spec:
  serviceName: "service-citizen"
  replicas: 1
  template:
    metadata:
      labels:
        role: services.citizen
    spec:
      containers:
        - name: citizenbudget-services-citizen
          image: lukasztomalczyk/citizenbudget.services.citizen:1.1
          imagePullPolicy: Always
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          volumeMounts:
          - name: config
            mountPath: /app/appsettings.Production.json
            #subPath: appsettings.Production.json
      volumes:
      - name: config
        configMap:
          name: citizen-service-settings-env-production