apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    name: rabbitmq
spec:
  ports:
  - port: 15672
    targetPort: 8080
  - port: 5672
    targetPort: 5672
  clusterIP: None
  selector:
    role: rabbitmq.service
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq-service
spec:
  serviceName: rabbitmq-service
  replicas: 1
  template:
    metadata:
      labels:
        role: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production