kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq.service.volume.claim
spec:
  volumeName: rabbitmq.persistent.volume
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi