apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul
        command: ["/bin/sh", "-c"]
        args: ["consul agent -server -bootstrap -ui -client=0.0.0.0 --data-dir /consul"]
        ports:
        - containerPort: 8500
        volumeMounts:
            - name: consul-storage
              mountPath: /consul/
      volumes:
        - name: consul-storage
          persistentVolumeClaim:
            claimName: consul.service.volume.claim
# kubectl expose deployment consul --type=NodePort --name=consul-service --namespace=citizen-budget
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul.persistent.volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/data/consul
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - develop-server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: consul.service.volume.claim
spec:
  volumeName: consul.persistent.volume
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi