apiVersion: v1
kind: Service
metadata:
  name: consul-service
  labels:
    name: consul-service
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - nodePort: 31250
    name: external
    port: 8500
    protocol: TCP
    targetPort: 8500
  - port: 8500
    targetPort: 8500
    name: container
  selector:
    role: consul.service
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul-service
spec:
  serviceName: consul-service
  replicas: 1
  template:
    metadata:
      labels:
        role: consul-service
    spec:
      containers:
        - name: consul
          image: consul
          command: ["/bin/sh", "-c"]
          args: ["consul agent -server -bootstrap -ui -client=0.0.0.0 --data-dir /consul"]
          ports:
            - containerPort: 8500
              name: connect
          volumeMounts:
            - name: consul-storage
              mountPath: /consul/
      volumes:
        - name: consul-storage
          persistentVolumeClaim:
            claimName: consul.service.volume.claim