apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-services-deployment
spec:
  selector:
    matchLabels:
      app: citizen.services
  replicas: 1
  template:
    metadata:
      labels:
        app: citizen.services
    spec:
      containers:
      - name: citizen
        image: lukasztomalczyk/citizenbudget.services.citizen:1.2
        ports:
        - containerPort: 80