apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-services-deployment
spec:
  selector:
    matchLabels:
      app: citizen.services
  replicas: 1
  template:
    metadata:
      labels:
        app: citizen.services
    spec:
      containers:
      - name: citizen
        image: lukasztomalczyk/citizenbudget.services.citizen:1.4
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          volumeMounts:
          - name: config
            mountPath: /app/appsettings.Production.json
            subPath: appsettings.Production.json
      volumes:
      - name: config
        configMap:
          name: citizen-service-settings-env-production