 apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config-settings
  namespace: citizen-budget
data: 
  config.json: |-  
   {
      "http_config": {
        "response_headers": {
          "Access-Control-Allow-Origin": "*",
	  "Access-Control-Request-Headers": "Access-Control-Allow-Origin"
        }
      }
    }
