apiVersion: v1
kind: Service
metadata:
  name: consul-service
  labels:
    name: consul-service
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - nodePort: 32250
    name: external
    port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    role: consul