apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore-deployment
spec:
  selector:
    matchLabels:
      app: eventstore-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eventstore-deployment
    spec:
      dnsPolicy: Default
      terminationGracePeriodSeconds: 10
      containers:
        - name: eventstore
          image: eventstore/eventstore
          ports:
            - containerPort: 2113
              name: first
            - containerPort: 1113
              name: second
          env:
            - name: EVENTSTORE_CLUSTER_GOSSIP_PORT
              value: "2112"
          volumeMounts:
            - name: eventstore-storage
              mountPath: /data/eventstore/db
      volumes:
        - name: eventstore-storage
          persistentVolumeClaim:
            claimName: eventstore-local-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eventstore-persistent-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/data/eventstore
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - develop-server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eventstore-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
---