apiVersion: v1
kind: ConfigMap
metadata:
  name: web-angular-settings-env-production
  namespace: citizen-budget
data: 
  appsettings.Production.json: |-
    export const environment = {
      production: true,
      consul_host: '172.18.0.6',
      consul_port: '8500',
      api_gateway_host: '10.152.183.235',
      api_gateway_port: '5000',
      api_gateway_protocol: 'http',
      signalr_notifications: 'notifications/notifications',
      citizen_service_create_citizen:  'api/citizen/createcitizen/',
    };

